name: Ralph on Rails
description: "I'm a Ruby on Rails developer in Sydney, Australia."
meta_description: "Ralph on Rails - My Ruby on Rails Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://www.ralphonrails.com'
author:         'Ralph Wintle'
